/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www;

import com.googleapis.www.controllers.*;
import com.googleapis.www.http.client.HttpClient;

public class AdExchangeBuyerAPIClient {
    /**
     * Singleton access to Accounts controller
     * @return	Returns the AccountsController instance 
     */
    public AccountsController getAccounts() {
        return AccountsController.getInstance();
    }

    /**
     * Singleton access to BillingInfo controller
     * @return	Returns the BillingInfoController instance 
     */
    public BillingInfoController getBillingInfo() {
        return BillingInfoController.getInstance();
    }

    /**
     * Singleton access to Budget controller
     * @return	Returns the BudgetController instance 
     */
    public BudgetController getBudget() {
        return BudgetController.getInstance();
    }

    /**
     * Singleton access to Creatives controller
     * @return	Returns the CreativesController instance 
     */
    public CreativesController getCreatives() {
        return CreativesController.getInstance();
    }

    /**
     * Singleton access to DirectDeals controller
     * @return	Returns the DirectDealsController instance 
     */
    public DirectDealsController getDirectDeals() {
        return DirectDealsController.getInstance();
    }

    /**
     * Singleton access to PerformanceReport controller
     * @return	Returns the PerformanceReportController instance 
     */
    public PerformanceReportController getPerformanceReport() {
        return PerformanceReportController.getInstance();
    }

    /**
     * Singleton access to PretargetingConfig controller
     * @return	Returns the PretargetingConfigController instance 
     */
    public PretargetingConfigController getPretargetingConfig() {
        return PretargetingConfigController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public AdExchangeBuyerAPIClient() {
    }

    /**
     * Client initialization constructor 
     */     
    public AdExchangeBuyerAPIClient(String oAuthAccessToken) {
        this();
        Configuration.oAuthAccessToken = oAuthAccessToken;
    }
}