/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AccountsList 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5390097614323261088L;
    private List<Account> items;
    private String kind = "adexchangebuyer#accountsList";
    /** GETTER
     * A list of accounts.
     */
    @JsonGetter("items")
    public List<Account> getItems ( ) { 
        return this.items;
    }
    
    /** SETTER
     * A list of accounts.
     */
    @JsonSetter("items")
    public void setItems (List<Account> value) { 
        this.items = value;
        notifyObservers(this.items);
    }
 
    /** GETTER
     * Resource type.
     */
    @JsonGetter("kind")
    public String getKind ( ) { 
        return this.kind;
    }
    
    /** SETTER
     * Resource type.
     */
    @JsonSetter("kind")
    public void setKind (String value) { 
        this.kind = value;
        notifyObservers(this.kind);
    }
 
}
 