/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class BidderLocation 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5733347815568251680L;
    private Integer maximumQps;
    private String region;
    private String url;
    /** GETTER
     * The maximum queries per second the Ad Exchange will send.
     */
    @JsonGetter("maximumQps")
    public Integer getMaximumQps ( ) { 
        return this.maximumQps;
    }
    
    /** SETTER
     * The maximum queries per second the Ad Exchange will send.
     */
    @JsonSetter("maximumQps")
    public void setMaximumQps (Integer value) { 
        this.maximumQps = value;
        notifyObservers(this.maximumQps);
    }
 
    /** GETTER
     * The geographical region the Ad Exchange should send requests from. Only used by some quota systems, but always setting the value is recommended. Allowed values:  
     * - ASIA 
     * - EUROPE 
     * - US_EAST 
     * - US_WEST
     */
    @JsonGetter("region")
    public String getRegion ( ) { 
        return this.region;
    }
    
    /** SETTER
     * The geographical region the Ad Exchange should send requests from. Only used by some quota systems, but always setting the value is recommended. Allowed values:  
     * - ASIA 
     * - EUROPE 
     * - US_EAST 
     * - US_WEST
     */
    @JsonSetter("region")
    public void setRegion (String value) { 
        this.region = value;
        notifyObservers(this.region);
    }
 
    /** GETTER
     * The URL to which the Ad Exchange will send bid requests.
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * The URL to which the Ad Exchange will send bid requests.
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
        notifyObservers(this.url);
    }
 
}
 