/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class BillingInfo 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4678973849846750502L;
    private Integer accountId;
    private String accountName;
    private List<String> billingId;
    private String kind = "adexchangebuyer#billingInfo";
    /** GETTER
     * Account id.
     */
    @JsonGetter("accountId")
    public Integer getAccountId ( ) { 
        return this.accountId;
    }
    
    /** SETTER
     * Account id.
     */
    @JsonSetter("accountId")
    public void setAccountId (Integer value) { 
        this.accountId = value;
        notifyObservers(this.accountId);
    }
 
    /** GETTER
     * Account name.
     */
    @JsonGetter("accountName")
    public String getAccountName ( ) { 
        return this.accountName;
    }
    
    /** SETTER
     * Account name.
     */
    @JsonSetter("accountName")
    public void setAccountName (String value) { 
        this.accountName = value;
        notifyObservers(this.accountName);
    }
 
    /** GETTER
     * A list of adgroup IDs associated with this particular account. These IDs may show up as part of a realtime bidding BidRequest, which indicates a bid request for this account.
     */
    @JsonGetter("billingId")
    public List<String> getBillingId ( ) { 
        return this.billingId;
    }
    
    /** SETTER
     * A list of adgroup IDs associated with this particular account. These IDs may show up as part of a realtime bidding BidRequest, which indicates a bid request for this account.
     */
    @JsonSetter("billingId")
    public void setBillingId (List<String> value) { 
        this.billingId = value;
        notifyObservers(this.billingId);
    }
 
    /** GETTER
     * Resource type.
     */
    @JsonGetter("kind")
    public String getKind ( ) { 
        return this.kind;
    }
    
    /** SETTER
     * Resource type.
     */
    @JsonSetter("kind")
    public void setKind (String value) { 
        this.kind = value;
        notifyObservers(this.kind);
    }
 
}
 