/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class BillingInfoList 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5358069965766199563L;
    private List<BillingInfo> items;
    private String kind = "adexchangebuyer#billingInfoList";
    /** GETTER
     * A list of billing info relevant for your account.
     */
    @JsonGetter("items")
    public List<BillingInfo> getItems ( ) { 
        return this.items;
    }
    
    /** SETTER
     * A list of billing info relevant for your account.
     */
    @JsonSetter("items")
    public void setItems (List<BillingInfo> value) { 
        this.items = value;
        notifyObservers(this.items);
    }
 
    /** GETTER
     * Resource type.
     */
    @JsonGetter("kind")
    public String getKind ( ) { 
        return this.kind;
    }
    
    /** SETTER
     * Resource type.
     */
    @JsonSetter("kind")
    public void setKind (String value) { 
        this.kind = value;
        notifyObservers(this.kind);
    }
 
}
 