/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Budget 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5377609290388648961L;
    private String accountId;
    private String billingId;
    private String budgetAmount;
    private String currencyCode;
    private String id;
    private String kind = "adexchangebuyer#budget";
    /** GETTER
     * The id of the account. This is required for get and update requests.
     */
    @JsonGetter("accountId")
    public String getAccountId ( ) { 
        return this.accountId;
    }
    
    /** SETTER
     * The id of the account. This is required for get and update requests.
     */
    @JsonSetter("accountId")
    public void setAccountId (String value) { 
        this.accountId = value;
        notifyObservers(this.accountId);
    }
 
    /** GETTER
     * The billing id to determine which adgroup to provide budget information for. This is required for get and update requests.
     */
    @JsonGetter("billingId")
    public String getBillingId ( ) { 
        return this.billingId;
    }
    
    /** SETTER
     * The billing id to determine which adgroup to provide budget information for. This is required for get and update requests.
     */
    @JsonSetter("billingId")
    public void setBillingId (String value) { 
        this.billingId = value;
        notifyObservers(this.billingId);
    }
 
    /** GETTER
     * The budget amount to apply for the billingId provided. This is required for update requests.
     */
    @JsonGetter("budgetAmount")
    public String getBudgetAmount ( ) { 
        return this.budgetAmount;
    }
    
    /** SETTER
     * The budget amount to apply for the billingId provided. This is required for update requests.
     */
    @JsonSetter("budgetAmount")
    public void setBudgetAmount (String value) { 
        this.budgetAmount = value;
        notifyObservers(this.budgetAmount);
    }
 
    /** GETTER
     * The currency code for the buyer. This cannot be altered here.
     */
    @JsonGetter("currencyCode")
    public String getCurrencyCode ( ) { 
        return this.currencyCode;
    }
    
    /** SETTER
     * The currency code for the buyer. This cannot be altered here.
     */
    @JsonSetter("currencyCode")
    public void setCurrencyCode (String value) { 
        this.currencyCode = value;
        notifyObservers(this.currencyCode);
    }
 
    /** GETTER
     * The unique id that describes this item.
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * The unique id that describes this item.
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
        notifyObservers(this.id);
    }
 
    /** GETTER
     * The kind of the resource, i.e. "adexchangebuyer#budget".
     */
    @JsonGetter("kind")
    public String getKind ( ) { 
        return this.kind;
    }
    
    /** SETTER
     * The kind of the resource, i.e. "adexchangebuyer#budget".
     */
    @JsonSetter("kind")
    public void setKind (String value) { 
        this.kind = value;
        notifyObservers(this.kind);
    }
 
}
 