/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreativesList 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5436402216374211465L;
    private List<Creative> items;
    private String kind = "adexchangebuyer#creativesList";
    private String nextPageToken;
    /** GETTER
     * A list of creatives.
     */
    @JsonGetter("items")
    public List<Creative> getItems ( ) { 
        return this.items;
    }
    
    /** SETTER
     * A list of creatives.
     */
    @JsonSetter("items")
    public void setItems (List<Creative> value) { 
        this.items = value;
        notifyObservers(this.items);
    }
 
    /** GETTER
     * Resource type.
     */
    @JsonGetter("kind")
    public String getKind ( ) { 
        return this.kind;
    }
    
    /** SETTER
     * Resource type.
     */
    @JsonSetter("kind")
    public void setKind (String value) { 
        this.kind = value;
        notifyObservers(this.kind);
    }
 
    /** GETTER
     * Continuation token used to page through creatives. To retrieve the next page of results, set the next request's "pageToken" value to this.
     */
    @JsonGetter("nextPageToken")
    public String getNextPageToken ( ) { 
        return this.nextPageToken;
    }
    
    /** SETTER
     * Continuation token used to page through creatives. To retrieve the next page of results, set the next request's "pageToken" value to this.
     */
    @JsonSetter("nextPageToken")
    public void setNextPageToken (String value) { 
        this.nextPageToken = value;
        notifyObservers(this.nextPageToken);
    }
 
}
 