/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Dimension 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5316249099303197593L;
    private String height;
    private String width;
    /** GETTER
     * Height in pixels.
     */
    @JsonGetter("height")
    public String getHeight ( ) { 
        return this.height;
    }
    
    /** SETTER
     * Height in pixels.
     */
    @JsonSetter("height")
    public void setHeight (String value) { 
        this.height = value;
        notifyObservers(this.height);
    }
 
    /** GETTER
     * Width in pixels.
     */
    @JsonGetter("width")
    public String getWidth ( ) { 
        return this.width;
    }
    
    /** SETTER
     * Width in pixels.
     */
    @JsonSetter("width")
    public void setWidth (String value) { 
        this.width = value;
        notifyObservers(this.width);
    }
 
}
 