/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DirectDealsList 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4689833262150642704L;
    private List<DirectDeal> directDeals;
    private String kind = "adexchangebuyer#directDealsList";
    /** GETTER
     * A list of direct deals relevant for your account.
     */
    @JsonGetter("directDeals")
    public List<DirectDeal> getDirectDeals ( ) { 
        return this.directDeals;
    }
    
    /** SETTER
     * A list of direct deals relevant for your account.
     */
    @JsonSetter("directDeals")
    public void setDirectDeals (List<DirectDeal> value) { 
        this.directDeals = value;
        notifyObservers(this.directDeals);
    }
 
    /** GETTER
     * Resource type.
     */
    @JsonGetter("kind")
    public String getKind ( ) { 
        return this.kind;
    }
    
    /** SETTER
     * Resource type.
     */
    @JsonSetter("kind")
    public void setKind (String value) { 
        this.kind = value;
        notifyObservers(this.kind);
    }
 
}
 