/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DisapprovalReason 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5627029665698679226L;
    private List<String> details;
    private String reason;
    /** GETTER
     * Additional details about the reason for disapproval.
     */
    @JsonGetter("details")
    public List<String> getDetails ( ) { 
        return this.details;
    }
    
    /** SETTER
     * Additional details about the reason for disapproval.
     */
    @JsonSetter("details")
    public void setDetails (List<String> value) { 
        this.details = value;
        notifyObservers(this.details);
    }
 
    /** GETTER
     * The categorized reason for disapproval.
     */
    @JsonGetter("reason")
    public String getReason ( ) { 
        return this.reason;
    }
    
    /** SETTER
     * The categorized reason for disapproval.
     */
    @JsonSetter("reason")
    public void setReason (String value) { 
        this.reason = value;
        notifyObservers(this.reason);
    }
 
}
 