/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PerformanceReportList 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5302662003594255502L;
    private String kind = "adexchangebuyer#performanceReportList";
    private List<PerformanceReport> performanceReport;
    /** GETTER
     * Resource type.
     */
    @JsonGetter("kind")
    public String getKind ( ) { 
        return this.kind;
    }
    
    /** SETTER
     * Resource type.
     */
    @JsonSetter("kind")
    public void setKind (String value) { 
        this.kind = value;
        notifyObservers(this.kind);
    }
 
    /** GETTER
     * A list of performance reports relevant for the account.
     */
    @JsonGetter("performanceReport")
    public List<PerformanceReport> getPerformanceReport ( ) { 
        return this.performanceReport;
    }
    
    /** SETTER
     * A list of performance reports relevant for the account.
     */
    @JsonSetter("performanceReport")
    public void setPerformanceReport (List<PerformanceReport> value) { 
        this.performanceReport = value;
        notifyObservers(this.performanceReport);
    }
 
}
 