# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApiTitle
  class CreateNewNoteRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :body

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["title"] = "title"
        @_hash["body"] = "body"
      end
      @_hash
    end

    def initialize(title = nil,
                   body = nil)
      @title = title
      @body = body
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      title = hash['title']
      body = hash['body']

      # Create object from extracted values
      CreateNewNoteRequest.new(title,
                               body)
    end
  end
end
