# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApiTitle
  class GetUsersResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :joined

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["name"] = "name"
        @_hash["image"] = "image"
        @_hash["joined"] = "joined"
      end
      @_hash
    end

    def initialize(name = nil,
                   image = nil,
                   joined = nil)
      @name = name
      @image = image
      @joined = joined
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      name = hash['name']
      image = hash['image']
      joined = hash['joined']

      # Create object from extracted values
      GetUsersResponse.new(name,
                           image,
                           joined)
    end
  end
end
