# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApiTitle
  class New < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :counter

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["counter"] = "counter"
      end
      @_hash
    end

    def initialize(counter = nil)
      @counter = counter
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      counter = hash['counter']

      # Create object from extracted values
      New.new(counter)
    end
  end
end
