# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApiTitle
  class NoteData < BaseModel
    # Unique identifier
    # @return [Float]
    attr_accessor :id

    # Single line description
    # @return [String]
    attr_accessor :title

    # Full description of the note which supports Markdown.
    # @return [String]
    attr_accessor :body

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["id"] = "id"
        @_hash["title"] = "title"
        @_hash["body"] = "body"
      end
      @_hash
    end

    def initialize(id = nil,
                   title = nil,
                   body = nil)
      @id = id
      @title = title
      @body = body
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      id = hash['id']
      title = hash['title']
      body = hash['body']

      # Create object from extracted values
      NoteData.new(id,
                   title,
                   body)
    end
  end
end
