# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApiTitle
  class Sample2Request < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :array_count

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["array_count"] = "arrayCount"
      end
      @_hash
    end

    def initialize(array_count = nil)
      @array_count = array_count
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      array_count = hash['arrayCount']

      # Create object from extracted values
      Sample2Request.new(array_count)
    end
  end
end
