# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApiTitle
  class SortEnum
    # TODO: Write general description for NAME
    # TODO: Write general description for JOINED
    # TODO: Write general description for ENUM_JOINED
    # TODO: Write general description for AGE
    # TODO: Write general description for ENUM_AGE
    # TODO: Write general description for LOCATION
    # TODO: Write general description for ENUM_LOCATION
    # TODO: Write general description for PLAN
    # TODO: Write general description for ENUM_PLAN
    SORT_ENUM = [NAME = 'name', JOINED = 'joined', ENUM_JOINED = '-joined', AGE = 'age', ENUM_AGE = '-age', LOCATION = 'location', ENUM_LOCATION = '-location', PLAN = 'plan', ENUM_PLAN = '-plan']
  end
end