# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApiTitle
  class UpdateANoteRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["title"] = "title"
      end
      @_hash
    end

    def initialize(title = nil)
      @title = title
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      title = hash['title']

      # Create object from extracted values
      UpdateANoteRequest.new(title)
    end
  end
end
