# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApiTitle
  class UpdateANoteRequest7 < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :body

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["body"] = "body"
      end
      @_hash
    end

    def initialize(body = nil)
      @body = body
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      body = hash['body']

      # Create object from extracted values
      UpdateANoteRequest7.new(body)
    end
  end
end
