# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

require_relative 'controller_test_base'

class TagsAndTaggingLongTitleControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.tags_and_tagging_long_title
  end

  # Get a list of bars
  def test_tags_1()

    # Perform the API call through the SDK function
    result = self.class.controller.get_tags()

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = nil

    assert(TestHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    assert_equal('["tag1", "tag2", "tag3"]', @response_catcher.response.raw_body)
  end

end
