# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'api_title/api_helper.rb'
require_relative 'api_title/api_title_client.rb'

# Http
require_relative 'api_title/http/http_call_back.rb'
require_relative 'api_title/http/http_client.rb'
require_relative 'api_title/http/http_method_enum.rb'
require_relative 'api_title/http/http_request.rb'
require_relative 'api_title/http/http_response.rb'
require_relative 'api_title/http/http_context.rb'
require_relative 'api_title/http/faraday_client.rb'
require_relative 'api_title/http/auth/o_auth_2.rb'

# Models
require_relative 'api_title/models/base_model.rb'
require_relative 'api_title/models/note_data.rb'
require_relative 'api_title/models/create_new_note_request.rb'
require_relative 'api_title/models/create_new_note_request_3.rb'
require_relative 'api_title/models/update_a_note_request.rb'
require_relative 'api_title/models/update_a_note_request_7.rb'
require_relative 'api_title/models/get_users_response.rb'
require_relative 'api_title/models/sample_2_request.rb'
require_relative 'api_title/models/new.rb'
require_relative 'api_title/models/sort_enum.rb'

# Exceptions
require_relative 'api_title/exceptions/api_exception.rb'

require_relative 'api_title/configuration.rb'

# Controllers
require_relative 'api_title/controllers/base_controller.rb'
require_relative 'api_title/controllers/notes_controller.rb'
require_relative 'api_title/controllers/users_ggg_controller.rb'
require_relative 'api_title/controllers/tags_and_tagging_long_title_controller.rb'
require_relative 'api_title/controllers/api_controller.rb'
