<?php
/*
 * HelloWorldLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HelloWorldLib\Controllers;

use HelloWorldLib\APIException;
use HelloWorldLib\APIHelper;
use HelloWorldLib\Configuration;
use HelloWorldLib\Models;
use HelloWorldLib\Exceptions;
use HelloWorldLib\Http\HttpRequest;
use HelloWorldLib\Http\HttpResponse;
use HelloWorldLib\Http\HttpMethod;
use HelloWorldLib\Http\HttpContext;
use HelloWorldLib\OAuthManager;
use Unirest\Request;

/**
 * @todo Add a general description for this controller.
 */
class OAuthAuthorizationController extends BaseController
{
    /**
     * @var OAuthAuthorizationController The reference to *Singleton* instance of this class
     */
    private static $instance;

    /**
     * Returns the *Singleton* instance of this class.
     * @return OAuthAuthorizationController The *Singleton* instance.
     */
    public static function getInstance()
    {
        if (null === static::$instance) {
            static::$instance = new static();
        }
        
        return static::$instance;
    }

    /**
     * Create a new OAuth 2 token.
     *
     * @param string $authorization Authorization header in Basic auth format
     * @param string $code          Authorization Code
     * @param string $redirectUri   Redirect Uri
     * @param    array  $fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return mixed response from the API call
     * @throws APIException Thrown if API call fails
     */
    public function createRequestToken(
        $authorization,
        $code,
        $redirectUri,
        $fieldParameters = null
    ) {

        //the base uri for api requests
        $_queryBuilder = Configuration::$BASEURI;
        
        //prepare query string for API call
        $_queryBuilder = $_queryBuilder.'/wqweqwe';

        //validate and preprocess url
        $_queryUrl = APIHelper::cleanUrl($_queryBuilder);

        //prepare headers
        $_headers = array (
            'user-agent'    => 'APIMATIC 2.0',
            'Accept'        => 'application/json',
            'Authorization'   => $authorization
        );

        //prepare parameters
        $_parameters = array (
            'grant_type'    => 'authorization_code',
            'code'          => $code,
            'redirect_uri'  => $redirectUri
        );

        //call on-before Http callback
        $_httpRequest = new HttpRequest(HttpMethod::POST, $_headers, $_queryUrl, $_parameters);
        if ($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnBeforeRequest($_httpRequest);
        }

        //and invoke the API call request to fetch the response
        $response = Request::post($_queryUrl, $_headers, Request\Body::Form($_parameters));

        $_httpResponse = new HttpResponse($response->code, $response->headers, $response->raw_body);
        $_httpContext = new HttpContext($_httpRequest, $_httpResponse);

        //call on-after Http callback
        if ($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnAfterRequest($_httpContext);
        }

        //Error handling using HTTP status codes
        if ($response->code == 400) {
            throw new Exceptions\OAuthProviderException('OAuth 2 provider returned an error.', $_httpContext);
        }

        if ($response->code == 401) {
            throw new Exceptions\OAuthProviderException(
                'OAuth 2 provider says client authentication failed.',
                $_httpContext
            );
        }

        //handle errors defined at the API level
        $this->validateResponse($_httpResponse, $_httpContext);

        $mapper = $this->getJsonMapper();

        return $mapper->mapClass($response->body, 'HelloWorldLib\\Models\\OAuthToken');
    }

    /**
     * Obtain a new access token using a refresh token
     *
     * @param string $authorization Authorization header in Basic auth format
     * @param string $refreshToken  Refresh token
     * @param string $scope         (optional) Requested scopes as a space-delimited list.
     * @param    array  $fieldParameters    Additional optional form parameters are supported by this endpoint
     * @return mixed response from the API call
     * @throws APIException Thrown if API call fails
     */
    public function createRefreshToken(
        $authorization,
        $refreshToken,
        $scope = null,
        $fieldParameters = null
    ) {

        //the base uri for api requests
        $_queryBuilder = Configuration::$BASEURI;
        
        //prepare query string for API call
        $_queryBuilder = $_queryBuilder.'/wqweqwe';

        //validate and preprocess url
        $_queryUrl = APIHelper::cleanUrl($_queryBuilder);

        //prepare headers
        $_headers = array (
            'user-agent'    => 'APIMATIC 2.0',
            'Accept'        => 'application/json',
            'Authorization'   => $authorization
        );

        //prepare parameters
        $_parameters = array (
            'grant_type'    => 'refresh_token',
            'refresh_token' => $refreshToken,
            'scope'         => $scope
        );

        //call on-before Http callback
        $_httpRequest = new HttpRequest(HttpMethod::POST, $_headers, $_queryUrl, $_parameters);
        if ($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnBeforeRequest($_httpRequest);
        }

        //and invoke the API call request to fetch the response
        $response = Request::post($_queryUrl, $_headers, Request\Body::Form($_parameters));

        $_httpResponse = new HttpResponse($response->code, $response->headers, $response->raw_body);
        $_httpContext = new HttpContext($_httpRequest, $_httpResponse);

        //call on-after Http callback
        if ($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnAfterRequest($_httpContext);
        }

        //Error handling using HTTP status codes
        if ($response->code == 400) {
            throw new Exceptions\OAuthProviderException('OAuth 2 provider returned an error.', $_httpContext);
        }

        if ($response->code == 401) {
            throw new Exceptions\OAuthProviderException(
                'OAuth 2 provider says client authentication failed.',
                $_httpContext
            );
        }

        //handle errors defined at the API level
        $this->validateResponse($_httpResponse, $_httpContext);

        $mapper = $this->getJsonMapper();

        return $mapper->mapClass($response->body, 'HelloWorldLib\\Models\\OAuthToken');
    }
}
