/*
 * TestFlags
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example;

import android.content.Context;
import com.android.volley.RequestQueue;
import com.android.volley.toolbox.Volley;

import com.example.models.*;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://example.com/api";


    //retains status whether we have already initialized
    private static boolean initialized = false;
    private static RequestQueue requestQueue = null;

    //Initialization of configuration
    public static void initialize(Context context){
        requestQueue = Volley.newRequestQueue(context);
    
        initialized = true;
    }

    // volley request queue needs to be initialized before use
    public static RequestQueue getRequestQueue() {
        if(!initialized)
            throw new IllegalStateException("Must initialize before accessing request queue");
        return requestQueue;
    }

    //this is new
    //TODO: Replace the mnew with an appropriate value
    public static String mnew = "";

    //o
    //TODO: Replace the n8888REWVGVFGF with an appropriate value
    public static String n8888REWVGVFGF = "";

    //OAuth 2 Client ID
    //TODO: Replace the oAuthClientId with an appropriate value
    public static String oAuthClientId = "TODO: Replace";

    //OAuth 2 Client Secret
    //TODO: Replace the oAuthClientSecret with an appropriate value
    public static String oAuthClientSecret = "TODO: Replace";

    //OAuth 2 Redirection endpoint or Callback Uri
    //TODO: Replace the oAuthRedirectUri with an appropriate value
    public static String oAuthRedirectUri = "TODO: Replace";

    /**
     * OAuth 2 token
     */
    public static OAuthTokenModel oAuthToken = null;

    /**
     * OAuth token update callback
     */
    public static OAuthTokenUpdateCallBack oAuthTokenUpdateCallBack = null;

}
