/*
 * TestFlags
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example;

import com.example.models.OAuthTokenModel;

public interface OAuthTokenUpdateCallBack {

    void tokenUpdate(OAuthTokenModel oAuthToken);

}
