/*
 * HelloServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.examples.www.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SayHelloResponse 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5267133041691842865L;
    private String greeting;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("greeting")
    public String getGreeting ( ) { 
        return this.greeting;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("greeting")
    public void setGreeting (String value) { 
        this.greeting = value;
        notifyObservers(this.greeting);
    }
 
}
 