/*
 * AdExchangeBuyerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.googleapis.www.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.type.TypeReference;

import com.googleapis.www.*;
import com.googleapis.www.models.*;
import com.googleapis.www.exceptions.*;
import com.googleapis.www.http.client.HttpClient;
import com.googleapis.www.http.client.HttpContext;
import com.googleapis.www.http.request.HttpRequest;
import com.googleapis.www.http.response.HttpResponse;
import com.googleapis.www.http.response.HttpStringResponse;
import com.googleapis.www.http.client.APICallBack;

public class PerformanceReportController extends BaseController {    
    //private static variables for the singleton pattern
    private static Object syncObject = new Object();
    private static PerformanceReportController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the PerformanceReportController class 
     */
    public static PerformanceReportController getInstance() {
        synchronized (syncObject) {
            if (null == instance) {
                instance = new PerformanceReportController();
            }
        }
        return instance;
    }

    /**
     * Retrieves the authenticated user's list of performance metrics.
     * @param    accountId    Required parameter: The account id to get the reports.
     * @param    endDateTime    Required parameter: The end time of the report in ISO 8601 timestamp format using UTC.
     * @param    startDateTime    Required parameter: The start time of the report in ISO 8601 timestamp format using UTC.
     * @param    alt    Optional parameter: Data format for the response. (Acceptable values are: "json")
     * @param    fields    Optional parameter: Selector specifying which fields to include in a partial response.
     * @param    key    Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
     * @param    oauthToken    Optional parameter: OAuth 2.0 token for the current user.
     * @param    prettyPrint    Optional parameter: Returns response with indentations and line breaks.
     * @param    quotaUser    Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.
     * @param    userIp    Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.
     * @param    maxResults    Optional parameter: Maximum number of entries returned on one result page. If not set, the default is 100. Optional.
     * @param    pageToken    Optional parameter: A continuation token, used to page through performance reports. To retrieve the next page, set this parameter to the value of "nextPageToken" from the previous response. Optional.
     * @return    Returns the void response from the API call 
     */
    public void listPerformancereportAsync(
                final String accountId,
                final String endDateTime,
                final String startDateTime,
                final String alt,
                final String fields,
                final String key,
                final String oauthToken,
                final Boolean prettyPrint,
                final String quotaUser,
                final String userIp,
                final Integer maxResults,
                final String pageToken,
                final APICallBack<PerformanceReportList> callBack
    ) {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;
        
        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri);
        _queryBuilder.append("/performancereport");

        //process query parameters
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, new HashMap<String, Object>() {
            private static final long serialVersionUID = 5555101458579978581L;
            {
                    put( "accountId", accountId );
                    put( "endDateTime", endDateTime );
                    put( "startDateTime", startDateTime );
                    put( "alt", (alt != null) ? alt : "json" );
                    put( "fields", fields );
                    put( "key", key );
                    put( "oauth_token", oauthToken );
                    put( "prettyPrint", (prettyPrint != null) ? prettyPrint : true );
                    put( "quotaUser", quotaUser );
                    put( "userIp", userIp );
                    put( "maxResults", maxResults );
                    put( "pageToken", pageToken );
            }});
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>() {
            private static final long serialVersionUID = 4634565853640710086L;
            {
                    put( "user-agent", "APIMATIC 2.0" );
                    put( "accept", "application/json" );
                    put( "Authorization", String.format("Bearer %1$s", Configuration.oAuthAccessToken) );
            }
        };

        //prepare and invoke the API call request to fetch the response
        final HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        //invoke the callback before request if its not null
        if (getHttpCallBack() != null)
        {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        //invoke request and get response
        Runnable _responseTask = new Runnable() {
            public void run() {
                //make the API call
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //extract result from the http response
                            String _responseBody = ((HttpStringResponse)_response).getBody();
                            PerformanceReportList _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<PerformanceReportList>(){});

                            //let the caller know of the success
                            callBack.onSuccess(_context, _result);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (IOException ioException) {
                            //let the caller know of the caught IO Exception
                            callBack.onFailure(_context, ioException);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)	
                            {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

}