/*
 * HelloServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.examples.www;

import com.examples.www.controllers.*;
import com.examples.www.http.client.HttpClient;

public class HelloServiceClient {
    /**
     * Singleton access to HelloBinding controller
     * @return	Returns the HelloBindingController instance 
     */
    public HelloBindingController getHelloBinding() {
        return HelloBindingController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public HelloServiceClient() {
    }

}