# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApiTitle
  class ApiTitleClient
    # Singleton access to notes controller
    # @return [NotesController] Returns the controller instance
    def notes
      NotesController.instance
    end

    # Singleton access to users_ggg controller
    # @return [UsersGggController] Returns the controller instance
    def users_ggg
      UsersGggController.instance
    end

    # Singleton access to tags_and_tagging_long_title controller
    # @return [TagsAndTaggingLongTitleController] Returns the controller instance
    def tags_and_tagging_long_title
      TagsAndTaggingLongTitleController.instance
    end

    # Singleton access to client controller
    # @return [APIController] Returns the controller instance
    def client
      APIController.instance
    end

    # Returns the configuration class for easy access
    # @return [Configuration] Returns the actual configuration class
    def config
      Configuration
    end

    # Initializer with authentication and configuration parameters
    def initialize(o_auth_access_token: nil)
      Configuration.o_auth_access_token = o_auth_access_token if o_auth_access_token
    end
  end
end
