# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ApiTitle
  class Configuration
    # The base Uri for API calls
    @base_uri = 'https://api.example.com'

    # OAuth 2.0 Access Token
    @o_auth_access_token = 'TODO: Replace'

    # The attribute accessors for public properties
    class << self
      attr_accessor :array_serialization
      attr_accessor :base_uri
      attr_accessor :o_auth_access_token
    end
  end
end
