<?php
/*
 * HelloWorldLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HelloWorldLib\Models;

/**
 * OAuth 2 scopes supported by the API
 */
class OAuthScopeEnum
{
    /**
     * TODO: Write general description for this element
     */
    const Q = "sad";

    /**
     * TODO: Write general description for this element
     */
    const ASD = "sad";
}
