<?php
/*
 * HelloWorldLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HelloWorldLib;

use HelloWorldLib\Controllers;

/**
 * HelloWorldLib client class
 */
class HelloWorldClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $oAuthClientId = null,
        $oAuthClientSecret = null,
        $oAuthRedirectUri = null
    ) {
        Configuration::$oAuthClientId = $oAuthClientId ? $oAuthClientId : Configuration::$oAuthClientId;
        Configuration::$oAuthClientSecret = $oAuthClientSecret ? $oAuthClientSecret : Configuration::$oAuthClientSecret;
        Configuration::$oAuthRedirectUri = $oAuthRedirectUri ? $oAuthRedirectUri : Configuration::$oAuthRedirectUri;
    }
    /**
     * Singleton access to Helloworld controller
     * @return Controllers\HelloworldController The *Singleton* instance
     */
    public function getHelloworld()
    {
        return Controllers\HelloworldController::getInstance();
    }
    /**
     * Singleton access to OAuthAuthorization controller
     * @return Controllers\OAuthAuthorizationController The *Singleton* instance
     */
    public function getOAuthAuthorization()
    {
        return Controllers\OAuthAuthorizationController::getInstance();
    }

    /**
     * Get OAuth 2 authorization manager
     * @return OAuthManager
     */
    public function auth()
    {
        return OAuthManager::getInstance();
    }
}
