/*
 * TestFlags
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreateRequestTokenInput 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5663466835914339178L;
    private String grantType = "authorization_code";
    private String authorization;
    private String code;
    private String redirectUri;
    /** GETTER
     * Grant Type
     */
    @JsonGetter("grant_type")
    public String getGrantType ( ) { 
        return this.grantType;
    }
    
    /** SETTER
     * Grant Type
     */
    @JsonSetter("grant_type")
    private void setGrantType (String value) { 
        this.grantType = value;
        notifyObservers(this.grantType);
    }
 
    /** GETTER
     * Authorization header in Basic auth format
     */
    @JsonGetter("Authorization")
    public String getAuthorization ( ) { 
        return this.authorization;
    }
    
    /** SETTER
     * Authorization header in Basic auth format
     */
    @JsonSetter("Authorization")
    public void setAuthorization (String value) { 
        this.authorization = value;
        notifyObservers(this.authorization);
    }
 
    /** GETTER
     * Authorization Code
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * Authorization Code
     */
    @JsonSetter("code")
    public void setCode (String value) { 
        this.code = value;
        notifyObservers(this.code);
    }
 
    /** GETTER
     * Redirect Uri
     */
    @JsonGetter("redirect_uri")
    public String getRedirectUri ( ) { 
        return this.redirectUri;
    }
    
    /** SETTER
     * Redirect Uri
     */
    @JsonSetter("redirect_uri")
    public void setRedirectUri (String value) { 
        this.redirectUri = value;
        notifyObservers(this.redirectUri);
    }
 
}
 