/*
 * TestFlags
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TaskModel 
        extends BaseModel
        implements java.io.Serializable {
    private static final long serialVersionUID = 5223069153810215680L;
    private String mMessage;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("{ "message")
    public String getMMessage ( ) { 
        return this.mMessage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("{ "message")
    public void setMMessage (String value) { 
        this.mMessage = value;
        notifyObservers(this.mMessage);
    }
 
}
 